\c doggo_central;

INSERT INTO dog_clothes(name, description, price, link, image, is_fav) VALUES
('Rubber Ducky Raincoat', 'A water-resistant raincoat designed to protect your dog from getting osoaked on rainy day walks. easy to clean by hand washing. Laesh hole allows easy access to a collar without letting the rain in.', 11.99, 'https://www.chewy.com/frisco-rubber-ducky-dog-raincoat/dp/171275', 'https://www.pumpkin.care/wp-content/uploads/2022/07/frisco-rubber-ducky_best-dog-raincoats-171x300.jpg', TRUE),
('Cable Dog Sweater', 'A fashionable turtleneck sweater that will keep your dog warm. Create a perfect twinning moment with your furry friend!', 39.97, 'https://bananarepublicfactory.gapfactory.com/browse/product.do?pid=497336021&vid=1&tid=bfpl000030&kwid=1&ap=7&gclid=CjwKCAiArY2fBhB9EiwAWqHK6hGuGFPtTw5p6jju57cx8IAnfrKlCk6Gb08b_0r1Ywx-gpVoHBwtfhoCbP4QAvD_BwE&gclsrc=aw.ds#pdp-page-content', 'https://bananarepublicfactory.gapfactory.com/webcontent/0029/612/389/cn29612389.jpg', TRUE),
('Stripped Ribbed Turtleneck Sweater', 'Luxurious stripe design turtleneck to keep your friend looking cute and help them stay warm!', 33.00, 'https://miminkopet.com/products/stripe-ribbed-turtleneck-sweater-wine?variant=41568318259369&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&gclid=CjwKCAiArY2fBhB9EiwAWqHK6pCvk50EjQ3nOalaRvEuLLwP9R0BDTBudeUl43LaGbJKi_GcVwQaeRoCFNAQAvD_BwE', 'https://cdn.shopify.com/s/files/1/0564/1066/9225/products/StripeRibbedTurtleneckSweater-Wine2_1200x.jpg?v=1634837874', FALSE),
('Pink Colorblocked Reversible Dog Fleece Coat', 'Durable comfort offers protection from the cold weather of winter. Reversible design allows you to choose between fluffy fleece or water-resistant fabric. Two-way front zipper closure for easy dressing.', 24.99, 'https://www.petco.com/shop/en/petcostore/product/youly-the-nature-lover-pink-colorblocked-reversible-dog-fleece-coat-xx-small-3379407?cm_mmc=PSH%7cGGL%7cSPP%7cSBU04%7c0%7cOB-Youly%7cfsRgTcHoPTQHMvrUN9JGiU%7c%7c%7c0%7c0%7c%7c%7c18145358118&gclid=CjwKCAiArY2fBhB9EiwAWqHK6sSujnQPstjNjWCX9S0KNtSwRBUZFDrsCameUMVlaNX6jgg8de5TLxoCN7AQAvD_BwE&gclsrc=aw.ds', 'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_468,w_500/c_pad,h_468,w_500/l_bypetco-badge,fl_relative,w_0.20,g_south_east,e_sharpen/3379431-center-11', TRUE),
('Frisco Colorback Puffer Dog Jacket', 'The stylish colors and classic design make this piece an absolute no brainer for the cold weather seasons. Trips to the park, walks around the neighborhood or photo ops just got a lot more stylish. The pullover design makes getting in and out simple and fast, then when you are done, just toss it in the washing machine for easy cleaning.', 11.55, 'https://www.chewy.com/frisco-colorblock-puffer-dog-cat/dp/380044', 'https://image.chewy.com/is/image/catalog/353814_MAIN._AC_SL600_V1661865542_.jpg', TRUE),
('Teddy Sherpa Fleece Dog Jacket', 'Premium human ggrade teddy sherpa exterior. Soft polar feelce interior. Hole opening back of the neck for leash. Machine wash cold, tumble dry cold.', 23.00, 'https://www.sparkpaws.com/products/sherpa-dog-jacket-brown?variant=38460367044789&utm_source=google&utm_medium=organic&utm_campaign=US%20Feed&utm_content=Teddy%20Sherpa%20Fleece%20Dog%20Jacket%20-%20Brown&currency=USD&utm_source=google&utm_medium=paid&utm_campaign=16246195189&utm_content=&utm_term=&gadid=&gclid=CjwKCAiArY2fBhB9EiwAWqHK6obqxkf8B9G6y68Lq-gO1Y7Xog3MErvw6PTdJOJqc8BEGMzp8G6UzBoCNYsQAvD_BwE', 'https://cdn.shopify.com/s/files/1/1638/5471/products/1_1200x.jpg?v=1663932438', TRUE),
('Cotton Candy Dog Hoodie', 'Soft like cotton, sweet like candy. Calming fleece interior, makes your dog feel hugged. Deep V cut in the front for easy potty.', 20.00, 'https://www.sparkpaws.com/products/cotton-candy-color-block-hoodie?variant=38460333490357', 'https://cdn.shopify.com/s/files/1/1638/5471/products/DSC_0825_88d2b95a-03fb-4ead-a034-9d397a95d2d4_1200x.jpg?v=1666698075', TRUE),
('Velvet Dog Hoodie - Obsidian Black', 'Match your dog with this hoodie. Calming fleece interior. Dog approved by thousands of furry friends!', 20.00, 'https://www.sparkpaws.com/collections/dog-apparel/products/vintage-black-velvet-dog-hoodie', 'https://cdn.shopify.com/s/files/1/1638/5471/products/2_8fe62f7d-80b6-46d1-98b5-c548cb26dce9_1000x.jpg?v=1666793597', TRUE),
('Gradient Diamond Dog Sweater', 'Fashionable fur friends of all breeds and sizes can use a sweater or two in their winter wardrobe! This pullover design sweater is perfect for cold-weather adventures.', 12.07, 'https://www.chewy.com/frisco-gradient-diamond-dog-cat/dp/250309', 'https://image.chewy.com/is/image/catalog/223783_MAIN._AC_SL600_V1599570366_.jpg', FALSE),
('Dog Raincoat Hooded Slicker Poncho', 'Waterproof: crafted from 100% polyester material to keep your pet comfortable and dry even in the worst weather conditions. convenient lightweight slicker can be easily folded and stored away. Refelctive: Highly visible reflective material helps to keep your pet safe out in the night time.', 21.99, 'https://www.amazon.com/HDE-Raincoat-Slicker-X-Large-Puppies/dp/B079J4D965/ref=sr_1_4?c=ts&keywords=Dog%2BRaincoats&qid=1675876492&s=pet-supplies&sr=1-4&ts_id=3024174011&th=1', 'https://m.media-amazon.com/images/I/61fbNRac3dL._AC_SX679_.jpg', FALSE)
