\c doggo_central;

INSERT INTO items(name, description, price, link, image, is_fav, category) VALUES
('Rubber Ducky Raincoat', 'A water-resistant raincoat designed to protect your dog from getting osoaked on rainy day walks. easy to clean by hand washing. Laesh hole allows easy access to a collar without letting the rain in.', 11.99, 'https://www.chewy.com/frisco-rubber-ducky-dog-raincoat/dp/171275', 'https://www.pumpkin.care/wp-content/uploads/2022/07/frisco-rubber-ducky_best-dog-raincoats-171x300.jpg', TRUE, 'clothes'),
('Cable Dog Sweater', 'A fashionable turtleneck sweater that will keep your dog warm. Create a perfect twinning moment with your furry friend!', 39.97, 'https://bananarepublicfactory.gapfactory.com/browse/product.do?pid=497336021&vid=1&tid=bfpl000030&kwid=1&ap=7&gclid=CjwKCAiArY2fBhB9EiwAWqHK6hGuGFPtTw5p6jju57cx8IAnfrKlCk6Gb08b_0r1Ywx-gpVoHBwtfhoCbP4QAvD_BwE&gclsrc=aw.ds#pdp-page-content', 'https://bananarepublicfactory.gapfactory.com/webcontent/0029/612/389/cn29612389.jpg', TRUE, 'clothes'),
('Stripped Ribbed Turtleneck Sweater', 'Luxurious stripe design turtleneck to keep your friend looking cute and help them stay warm!', 33.00, 'https://miminkopet.com/products/stripe-ribbed-turtleneck-sweater-wine?variant=41568318259369&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&gclid=CjwKCAiArY2fBhB9EiwAWqHK6pCvk50EjQ3nOalaRvEuLLwP9R0BDTBudeUl43LaGbJKi_GcVwQaeRoCFNAQAvD_BwE', 'https://cdn.shopify.com/s/files/1/0564/1066/9225/products/StripeRibbedTurtleneckSweater-Wine2_1200x.jpg?v=1634837874', FALSE, 'clothes'),
('Pink Colorblocked Reversible Dog Fleece Coat', 'Durable comfort offers protection from the cold weather of winter. Reversible design allows you to choose between fluffy fleece or water-resistant fabric. Two-way front zipper closure for easy dressing.', 24.99, 'https://www.petco.com/shop/en/petcostore/product/youly-the-nature-lover-pink-colorblocked-reversible-dog-fleece-coat-xx-small-3379407?cm_mmc=PSH%7cGGL%7cSPP%7cSBU04%7c0%7cOB-Youly%7cfsRgTcHoPTQHMvrUN9JGiU%7c%7c%7c0%7c0%7c%7c%7c18145358118&gclid=CjwKCAiArY2fBhB9EiwAWqHK6sSujnQPstjNjWCX9S0KNtSwRBUZFDrsCameUMVlaNX6jgg8de5TLxoCN7AQAvD_BwE&gclsrc=aw.ds', 'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_468,w_500/c_pad,h_468,w_500/l_bypetco-badge,fl_relative,w_0.20,g_south_east,e_sharpen/3379431-center-11', TRUE, 'clothes'),
('Frisco Colorback Puffer Dog Jacket', 'The stylish colors and classic design make this piece an absolute no brainer for the cold weather seasons. Trips to the park, walks around the neighborhood or photo ops just got a lot more stylish. The pullover design makes getting in and out simple and fast, then when you are done, just toss it in the washing machine for easy cleaning.', 11.55, 'https://www.chewy.com/frisco-colorblock-puffer-dog-cat/dp/380044', 'https://image.chewy.com/is/image/catalog/353814_MAIN._AC_SL600_V1661865542_.jpg', TRUE, 'clothes'),
('Teddy Sherpa Fleece Dog Jacket', 'Premium human ggrade teddy sherpa exterior. Soft polar feelce interior. Hole opening back of the neck for leash. Machine wash cold, tumble dry cold.', 23.00, 'https://www.sparkpaws.com/products/sherpa-dog-jacket-brown?variant=38460367044789&utm_source=google&utm_medium=organic&utm_campaign=US%20Feed&utm_content=Teddy%20Sherpa%20Fleece%20Dog%20Jacket%20-%20Brown&currency=USD&utm_source=google&utm_medium=paid&utm_campaign=16246195189&utm_content=&utm_term=&gadid=&gclid=CjwKCAiArY2fBhB9EiwAWqHK6obqxkf8B9G6y68Lq-gO1Y7Xog3MErvw6PTdJOJqc8BEGMzp8G6UzBoCNYsQAvD_BwE', 'https://cdn.shopify.com/s/files/1/1638/5471/products/1_1200x.jpg?v=1663932438', TRUE, 'clothes'),
('Cotton Candy Dog Hoodie', 'Soft like cotton, sweet like candy. Calming fleece interior, makes your dog feel hugged. Deep V cut in the front for easy potty.', 20.00, 'https://www.sparkpaws.com/products/cotton-candy-color-block-hoodie?variant=38460333490357', 'https://cdn.shopify.com/s/files/1/1638/5471/products/DSC_0825_88d2b95a-03fb-4ead-a034-9d397a95d2d4_1200x.jpg?v=1666698075', TRUE, 'clothes'),
('Velvet Dog Hoodie - Obsidian Black', 'Match your dog with this hoodie. Calming fleece interior. Dog approved by thousands of furry friends!', 20.00, 'https://www.sparkpaws.com/collections/dog-apparel/products/vintage-black-velvet-dog-hoodie', 'https://cdn.shopify.com/s/files/1/1638/5471/products/2_8fe62f7d-80b6-46d1-98b5-c548cb26dce9_1000x.jpg?v=1666793597', TRUE, 'clothes'),
('Gradient Diamond Dog Sweater', 'Fashionable fur friends of all breeds and sizes can use a sweater or two in their winter wardrobe! This pullover design sweater is perfect for cold-weather adventures.', 12.07, 'https://www.chewy.com/frisco-gradient-diamond-dog-cat/dp/250309', 'https://image.chewy.com/is/image/catalog/223783_MAIN._AC_SL600_V1599570366_.jpg', FALSE, 'clothes'),
('Dog Raincoat Hooded Slicker Poncho', 'Waterproof: crafted from 100% polyester material to keep your pet comfortable and dry even in the worst weather conditions. convenient lightweight slicker can be easily folded and stored away. Refelctive: Highly visible reflective material helps to keep your pet safe out in the night time.', 21.99, 'https://www.amazon.com/HDE-Raincoat-Slicker-X-Large-Puppies/dp/B079J4D965/ref=sr_1_4?c=ts&keywords=Dog%2BRaincoats&qid=1675876492&s=pet-supplies&sr=1-4&ts_id=3024174011&th=1', 'https://m.media-amazon.com/images/I/61fbNRac3dL._AC_SX679_.jpg', FALSE, 'clothes'),
('Just Food For Dogs', 'This fresh dog food is crafted with human-grade ingredients that you can see. With a wide variety of recipes—including Chicken & White Rice, Beef & Russet Potato, Turkey & Whole Wheat Macaroni and Lamb & Brown Rice—your dog can experience all the yummy benefits of a fresh, whole food diet. Pantry Fresh meals are made completely free from preservatives.', 62.60, 'https://www.chewy.com/justfoodfordogs-pantry-fresh-human/dp/620086', 'https://image.chewy.com/is/image/catalog/620094_MAIN._AC_SL600_V1666296527_.jpg', TRUE, 'food'),
('Instinct Frozen Raw Bites Grain-Free Real Beef', 'Satisfy instinctual cravings with the power of raw nutrition and Instinct Frozen Raw Bites Grain-Free Real Beef Recipe Dog Food. These delectable bites are protein-packed with 85% meat and organs and 15% non-GMO fruits, vegetables, vitamins and minerals—so you can give your furry friend the nutrition her ancestors intended.', 39.99, 'https://www.chewy.com/instinct-frozen-raw-bites-grain-free/dp/170863', 'https://image.chewy.com/is/image/catalog/143996_MAIN._AC_SL600_V1668200067_.jpg', FALSE, 'food'),
('Hills Science Diet Adult Sensitive Stomach & Skin Tender Turkey- 12 cans', 'This canned dog food is slow-cooked in the USA and has an irresistible turkey flavor your pup would not be able to resist. It is specifically designed to help support adult dogs with sensitive tummies and skin with ingredients like easily digestible turkey, chicken and rice, plus healthy omega-6 fatty acids and vitamin E.', 38.04, 'https://www.chewy.com/hills-science-diet-adult-sensitive/dp/184533', 'https://image.chewy.com/is/image/catalog/157792_MAIN._AC_SL600_V1595601955_.jpg', TRUE, 'food'),
('Purina ONE SmartBlend Tender Cuts in Gravy Chicken & Brown Rice', 'Nutritionally complete for your adult dog. Made from select, high-quality ingredients plus vitamins and minerals, you can feel confident you are providing the nutrition your dog needs to promote a lifetime of good health.', 19.67, 'https://www.chewy.com/purina-one-smartblend-tender-cuts-in/dp/119431', 'https://image.chewy.com/is/image/catalog/91787_MAIN._AC_SL600_V1671734310_.jpg', FALSE, 'food'),
('Faux Fur Orthopedic Dog Bed', 'Made from human-grade memory foam all of our dog beds are designed to ease joint pain and provide maximum support for your four-legged friend.', 159.00, 'https://www.paw.com/products/puprug-faux-fur-orthopedic-dog-bed-curve-white?variant=15937463418929&nbt=nb%3Aadwords%3Ax%3A15283278849%3A%3A&nb_adtype=pla&nb_kwd=&nb_ti=&nb_mi=122089872&nb_pc=online&nb_pi=shopify_US_2082645442609_15937463418929&nb_ppi=&nb_placement=&nb_li_ms=&nb_lp_ms=&nb_fii=&nb_ap=&nb_mt=&tw_source=google&tw_adid=&tw_campaign=15283278849&gclid=CjwKCAiA0JKfBhBIEiwAPhZXD5KekwdDNvc1dDDEDHv2djdGidYwhNCocAuYkrDpMJaAiMp6Kw5J0hoC-5wQAvD_BwE', 'https://cdn.shopify.com/s/files/1/0810/5967/products/5_e37bd5b0-7c5c-4e34-aa94-7e9b1a797d8e.png?crop=center&height=650&v=1672161786&width=650', FALSE, 'other'),
('ANTI-ANXIETY CALMING BED FOR DOGS', 'Helps ground and relax your furry friends. The raised rim creates a sense of security and positively activates the nervous system, allowing your pooch to relax more easily, calm down quickly, and sleep more soundly.', 89.00, 'https://lucky-paws.co/products/calmingbed?currency=USD&utm_medium=cpc&utm_source=google&utm_campaign=Google%20Shopping&utm_source=google&utm_medium=paid&utm_campaign=17424626765&utm_content=&utm_term=&gadid=&gclid=CjwKCAiA0JKfBhBIEiwAPhZXD49FhuQKJ1YiG9zD9_HtUi_NK5w4kK1Rr7p2ygb7KVSSDrV1jeqfohoCk2QQAvD_BwE&variant=39749992054902', 'https://cdn.shopify.com/s/files/1/0550/0682/2518/products/Untitleddesign_20_f9890688-ed71-44db-917b-9a36e5fab3b4_2000x.png?v=1659030723', TRUE, 'other'),
('Max and Neo Double Handle Traffic Dog Leash Reflective', 'Our double handle traffic dog leash has all the features of top of the line dog leashes. It is 1" wide and made of 2mm thick but soft heavy duty nylon webbing designed to handle the largest dog breeds.', 15.99, 'https://www.amazon.com/dp/B019YPYG4W/ref=as_li_ss_tl?tag=202266-z0go01xl0r-20&linkCode=ll1', 'https://m.media-amazon.com/images/I/61yqWH+feJL._AC_SX679_.jpg', TRUE, 'other'),
('PetSafe Premier Nylon Dog Leash', 'Durability meets functionality with the PetSafe Premier Nylon Dog Leash. This soft, durable nylon leashes keep you in control when walking your dog.', 7.99, 'https://www.chewy.com/petsafe-premier-nylon-dog-leash/dp/52301?utm_source=partnerize&utm_medium=affiliates&utm_campaign=1100l79052&utm_content=0&clickref=1011lwzzJfFV&utm_term=1011lwzzJfFV', 'https://image.chewy.com/is/image/catalog/67364_MAIN._AC_SL600_V1619994124_.jpg', TRUE, 'other');

INSERT INTO comments(commenter, comment, item_id) VALUES 
('Jenny on the Block', 'My dog absoultely loves this dog food! Eats it up in seconds!', 11),
('Edgy from brooklyn', 'Nola looks so cute in her new coat. Highly recommend!', 10),
('Nikesh', 'My cousins dog loves their new hoodie! So soft.', 7),
('Dilruba', 'i WANTED A DOG SO BAD, i brought my cat this coat lolll', 6);


